config/routes.rb
ToDoListApp::Application.routes.draw do
  resources :lists

  resources :tasks
  devise_for :users

  root 'welcome#index'
  
  get 'lists/users/follow' => 'lists#follow', as: :follow

  get 'lists/users/unfollow' => 'lists#unfollow', as: :unfollow

  

end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" interface, and also to followers
  belongs_to :followable, :polymorphic => true
  belongs_to :follower,   :polymorphic => true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/list.rb
class List < ActiveRecord::Base
	has_many :tasks, :dependent => :destroy
    accepts_nested_attributes_for :tasks, :allow_destroy => true
	belongs_to :user
end

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :list
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  
  has_many :lists
  
  acts_as_followable
  acts_as_follower

  def self.search(search)
	  if search
	    find(:all, :conditions => ['first_name LIKE ?', "%#{search}%"])
	  else
	    find(:all)
	  end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:first_name, :last_name, :email, :password, :password_confirmation) }
  end

  def after_sign_in_path_for(resource) 
    lists_path
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def index
    @users = User.search(params[:search])
    @lists = current_user.lists
    @followers = current_user.followers
    @following = current_user.all_following
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
    @tasks = @list.tasks
  end

  # GET /lists/new
  def new
    @list = List.new
    # @list.tasks.build
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = current_user.lists.create(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to lists_path, notice: 'List was successfully created.' }
        format.json { render action: 'show', status: :created, location: @list }
      else
        format.html { render action: 'new' }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url }
      format.json { head :no_content }
    end
  end

  def follow
    @user = User.find(params[:id])
    current_user.follow(@user)
    redirect_to :back, notice: "You are now following to Harsha"

  end

  def unfollow
    @user = User.find(params[:id])
    current_user.stop_following(@user)
    redirect_to :back, notice: "You are not following to Harsha"
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:name, :description, tasks_attributes: [:id, :task_name, :_destroy])
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    # puts "#{current_user.inspect}"
    @tasks = Task.all
    # @pending_tasks = current_user.tasks.where(:done => false)
    # @done_tasks = current_user.tasks.where(:done => true)
    # @users = User.all
    # @followers = current_user.followers
    # puts "followers_ids #{@followers.inspect}"
    # @following = current_user.all_following
    # puts "I am following #{@following}"
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to tasks_path, notice: 'Task was successfully created.' }
        format.json { render action: 'show', status: :created, location: @task }
      else
        format.html { render action: 'new' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(:done => true)
        format.html { redirect_to :back}
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.json { head :no_content }
    end
  end

  # def follow
  #   @user = User.find(params[:id])
  #   current_user.follow(@user)
  #   redirect_to :back, notice: "You are now following to Harsha"

  # end

  # def unfollow
  #   @user = User.find(params[:id])
  #   current_user.stop_following(@user)
  #   redirect_to :back, notice: "You are not following to Harsha"
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:task_name, :done)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToDoListApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="wrapper">
	    <nav class="navbar navbar-inverse navbar-fixed-top">
	      <div class="container">
	        <div class="navbar-header">
	          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navigation">
	            <span class="sr-only">Toggle navigation</span>
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	          </button>
	          <!-- <a class="navbar-brand" href="#">ToDoListApp </a> -->
	          <%= link_to "ToDoListApp", lists_path, :class=>"navbar-brand" %>
	        </div>
	        <div class="collapse navbar-collapse" id="navigation">
	            <ul class="nav navbar-nav navbar-right">
  					<%= render 'devise/menu/registration_items' %>
  					<%= render 'devise/menu/login_items' %>
	            </ul>
	        </div>
	      </div>
	    </nav>
	    <header class="header">
	        <div class="container">
	        <br>
	        	<% if user_signed_in? %>
	        	<h2>Welcome <strong><%= current_user.first_name %> <%= current_user.last_name %></strong></h2> 
	        	<% end %>
		        <div id="flash">
		        	<% if notice %>
					  <p class="alert alert-success"><%= notice %></p>
					<% end %>
					<% if alert %>
					  <p class="alert alert-danger"><%= alert %></p>
					<% end %>
		        </div> 		
	          	<%= yield %>
	        </div>
	    </header>
	    <footer class="footer text-center">
	        <div class="container">
	            <small>© Copyright 2015. Crafted with love by Harsha</small>
	        </div>
	    </footer>
	</div>

	<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="exampleModalLabel">Sign in</h4>
      </div>
      <div class="modal-body">

      	<%= form_for(:user, :html=>{role: "form"}, :url => session_path(:user)) do |f| %>
			  <div class="form-group">
			    <label for="email">Email:</label>
			    <%= f.email_field :email, autofocus: true, :class=>"form-control", :id=>"email" %>
			  </div>
			  <div class="form-group">
			    <label for="pwd">Password:</label>
			    <%= f.password_field :password, autocomplete: "off", :class=>"form-control", :id=>"pwd" %>
			  </div>
			  <%= f.submit "Sign in", :class=>"btn btn-success" %>
		<% end %>
    
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
</body>
</html>



<script type="text/javascript">
$(document).ready(function(){
  setTimeout(function(){
    $('#flash').remove();
  }, 2000);
 })
</script>

<style>
ul.hmenu {
  list-style: none; 
  margin: 0 0 2em;
  padding: 0;
}

ul.hmenu li {
  display: inline;  
}
</style>

app/views/lists/_form.html.erb
<%= form_for @list, :html=>{role: "form"} do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% @list.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <label for="name">Name:</label>
    <%= f.text_field :name, autofocus: true, :class=>"form-control", :id=>"listname" %>
  </div>
  <div class="form-group">
    <label for="description">Description:</label>
    <%= f.text_area :description, autofocus: true, :class=>"form-control", :id=>"listdescription" %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-success" %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h4>Editing ToDoList</h4>

<%#= render 'form' %>

<%= nested_form_for @list, :html=>{role: "form"} do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% @list.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <label for="name">Name:</label>
    <%= f.text_field :name, autofocus: true, :class=>"form-control", :id=>"listname" %>
  </div>
  <div class="form-group">
    <label for="description">Description:</label>
    <%= f.text_area :description, autofocus: true, :class=>"form-control", :id=>"listdescription" %>
  </div>

  <%= f.fields_for :tasks do |builder| %>
  <div class="form-group">
    <label for="tname">Task Name:</label>
    <%= builder.text_field :task_name, :class=>"form-control", :id=>"tname" %>
    <%= builder.link_to_remove "Remove this task" %>
  </div>
  <% end %>
  <p><%= f.link_to_add "Add a task", :tasks %></p>
  <div class="actions">
    <%= f.submit class: "btn btn-success" %>
  </div>
<% end %>

<br><br>

<%= link_to 'Back', lists_path, class: "btn btn-primary" %>

app/views/lists/index.html.erb
<br>
<table class="table table-hover table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Action</th>
    </tr>
  </thead>

  <tbody>
    <% @lists.each do |l| %>
      <tr>
        <td><%= l.name %></td>
        <td><%= l.description %></td>
        <td><%= link_to 'View Tasks Status', l, class: "btn btn-warning" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'Create New List', new_list_path, :class=>"btn btn-success" %>
<br><br>
<h4>Listing Users</h4>
<%= form_tag lists_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil, class: "btn btn-primary" %>
  </p>
<% end %>

<table class="table table-hover table-bordered">
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Remark</th>
      <th>Follow / Unfollow</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |u| %>
    <% if current_user != u %>
      <tr>
        <td><%= u.first_name %></td>
        <td><%= u.last_name %></td>
        <% if u.following?(current_user) %>
          <td><%= u.first_name %> <%= u.last_name %> is folowing you.</td>
        <% elsif current_user.following?(u) %>
          <td>You are following <%= u.first_name %> <%= u.last_name %>.</td>
        <% else %>
          <td>N/A</td>
        <% end %>
        <% if current_user.following?(u) %>
          <td><%= link_to "Unfollow", {:controller => "lists", :action => "unfollow", :id=>u.id}, :class=> "btn btn-warning" %></td>
        <% else %>
          <td><%= link_to "Follow", {:controller => "lists", :action => "follow", :id=>u.id}, :class=> "btn btn-success" %></td>
        <% end %>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>

<h4>Listing ToDoLists</h4>

<table class="table table-hover table-bordered">
<% @followers.each do |f| %>
  <thead>
  <tr><th  colspan = "3"><%= f.first_name %> <%= f.last_name %></th></tr>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Action</th>
    </tr>
  </thead>

  <tbody>
    <% f.lists.each do |l| %>
      <tr>
        <td><%= l.name %></td>
        <td><%= l.description %></td>
        <td><%= link_to 'Add Tasks', edit_list_path(l), class: "btn btn-success" %></td>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>


<table class="table table-hover table-bordered">
<% @following.each do |f| %>
  <thead>
  <tr><th  colspan = "3"><%= f.first_name %> <%= f.last_name %></th></tr>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Action</th>
    </tr>
  </thead>

  <tbody>
    <% f.lists.each do |l| %>
      <tr>
        <td><%= l.name %></td>
        <td><%= l.description %></td>
        <td><%= link_to 'Add Tasks', edit_list_path(l), class: "btn btn-success" %></td>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>

<br>

app/views/lists/new.html.erb
<br>
<h4>Create New list</h4>

<%= render 'form' %>
<br>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @list.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @list.description %>
</p>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Task name</th>
      <th>Status</th>
      <th>Action</th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.task_name %></td>
        <% if task.done %>
        <td>Completed</td>
        <% else %>
        <td>Pending</td>
        <% end %> 
        <% if task.list.user_id == current_user.id %>
        <td><%= link_to "Mark as Done", task, :method => :patch, :class => "btn btn-success" %></td>
        <% else %>
        <td>N/A</td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%#= link_to 'Edit', edit_list_path(@list) %>
<%= link_to 'Back', lists_path, class: "btn btn-primary" %>

app/views/tasks/_form.html.erb
<%= form_for @task, :html=>{role: "form"} do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <!-- <%#= f.label :task_name %><br> -->
    <label for="email">Task Name:</label>
    <%= f.text_field :task_name, autofocus: true, :class=>"form-control", :id=>"taskname" %>
  </div>
  <!-- <div class="actions"> -->
    <%= f.submit class: "btn btn-success" %>
  <!-- </div> -->
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<br><br>
<h4>Listing Pending Tasks</h4>

<!-- <table class="table table-bordered">
  <thead>
    <tr>
      <th>Task name</th>
      <th>Status</th>
      <th>Action</th>
    </tr>
  </thead>

  <tbody>
    <%# @pending_tasks.each do |task| %>
      <tr>
        <td><%#= task.task_name %></td>
        <td>Pending</td> 
        <td><%#= link_to "Mark as Done", task, :method => :patch, :class => "btn btn-success" %></td>
      </tr>
    <%# end %>
  </tbody>
</table>
<br> -->
<%= link_to 'Add New Task', new_task_path, :class => "btn btn-primary" %>
<br><br>



<!-- <h4>Listing Completed Tasks</h4>

<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>Task name</th>
      <th>Status</th>
      <th>Action</th>
    </tr>
  </thead>

  <tbody>
    <%# @done_tasks.each do |t| %>
      <tr>
        <td><%#= t.task_name %></td>
        <td>Done</td>
        <td><%#= link_to 'Destroy', t, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" %></td>
      </tr>
    <%# end %>
  </tbody>
</table>
<br>
<br>

<h4>Follow known peoples:</h4>
<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Email</th>
      <th>Follow / Unfollow</th>
    </tr>
  </thead>

  <tbody>
    <%# @users.each do |u| %>
      <%# if current_user != u %>
        <tr>
          <td><%#= u.first_name %></td>
          <td><%#= u.last_name %></td>
          <td><%#= u.email %></td>
          <%# if current_user.following?(u) %>
          <td><%#= link_to "Unfollow", {:controller => "tasks", :action => "unfollow", :id=>u.id}, :class=> "btn btn-warning" %></td>
          <%# else %>
          <td><%#= link_to "Follow", {:controller => "tasks", :action => "follow", :id=>u.id}, :class=> "btn btn-success" %></td>
          <%# end %>
        </tr>
      <%# end %>
    <%# end %>
  </tbody>
</table>
<br>
<br>

<h4>View tasks of people you follow and are being followed by:</h4>

<table class="table table-bordered table-hover">
<%# @followers.each do |f| %>
  <thead>
  <tr><strong><th colspan = "2"><%#= f.first_name %> <%#= f.last_name %> - Follower</th></strong></tr>
    <tr>
      <th>Task Name</th>
      <th>Status</th>
    </tr>
  </thead>

  <tbody>
    
      
      <%# f.tasks.each do |t| %>
        <tr>
          <td><%#= t.task_name %></td>
          <%# if t.done %>
            <td>Completed</td>
          <%# else %>
            <td>Pending</td>
          <%# end %>
        </tr>
      <%# end %>
    <%# end %>
  </tbody>
</table>

<table class="table table-bordered table-hover">
<%# @following.each do |f| %>
  <thead>
  <tr><strong><th colspan = "2"><%#= f.first_name %> <%#= f.last_name %> - Followee</th></strong></tr>
    <tr>
      <th>Task Name</th>
      <th>Status</th>
    </tr>
  </thead>

  <tbody>
    
      
      <%# f.tasks.each do |t| %>
        <tr>
          <td><%#= t.task_name %></td>
          <%# if t.done %>
            <td>Completed</td>
          <%# else %>
            <td>Pending</td>
          <%# end %>
        </tr>
      <%# end %>
    <%# end %>
  </tbody>
</table> -->

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>
<br><br>
<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p>
  <strong>Task name:</strong>
  <%= @task.task_name %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/welcome/index.html.erb
<div class="col-md-5 col-md-offset-1">
        <div class="content">
          <div class="pull-middle">
            <h1 class="page-header">Create your own To Do List.</h1>
            <p class="lead">Sign up here and Go!.</p>
            <div class="panel panel-default well">
                <div class="panel-body">
                	

                	<!-- <form role="form" class="well"> -->
                	<%= form_for(:user, :html=>{role: "form"}, :url => registration_path(:user)) do |f| %>

                          <div class="form-group">
                            <label for="fname">First Name:</label>
                            <%= f.text_field :first_name, autofocus: true, :class=>"form-control", :id=>"fname" %>
                          </div>
                          <div class="form-group">
                            <label for="lname">Last Name:</label>
                            <%= f.text_field :last_name, :class=>"form-control", :id=>"lname" %>
                          </div>
						  <div class="form-group">
						    <label for="email">Email address:</label>
						    <%= f.email_field :email, autofocus: true, :class=>"form-control", :id=>"email" %>
						  </div>
						  <div class="form-group">
						    <label for="pwd">Password:</label>
						    <%= f.password_field :password, autocomplete: "off", :class=>"form-control", :id=>"pwd" %>
						  </div>

						  <div class="form-group">
						    <label for="pwd">Password confirmation:</label>
						    <%= f.password_field :password_confirmation, autocomplete: "off", :class=>"form-control", :id=>"pwdconf" %>
						  </div>

						  <%= f.submit "Sign up", :class=>"btn btn-success" %> 
						<% end %>
					<!-- </form> -->
                </div>
            </div>
          </div>              
        </div>
    </div>
    <div class="col-md-4 col-md-offset-1 text-center mt-100 mb-100">
        <div class="phone">
            <img class="img-responsive img-rounded" src="http://placemi.com/djlnr/263x480">
        </div>
</div>

app/views/welcome/login_modal.html.erb
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="exampleModalLabel">Sign in</h4>
      </div>
      <div class="modal-body">
        <form>
          <div class="form-group">
            <label for="recipient-name" class="control-label">Email:</label>
            <input type="text" class="form-control" id="recipient-name">
          </div>
          <div class="form-group">
            <label for="message-text" class="control-label">Password:</label>
            <textarea class="form-control" id="message-text"></textarea>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Sign in</button>
      </div>
    </div>
  </div>
</div>